name: flutter_google_login
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  
  firebase_auth: ^5.3.4
  firebase_core: ^3.9.0
  cloud_firestore: ^5.6.0
  firebase_messaging: ^15.1.6
  firebase_crashlytics: ^4.2.0
  firebase_remote_config: ^5.2.0
  
  google_sign_in: ^6.2.2

  kakao_flutter_sdk_user: ^1.9.6
  
  flutter_naver_login: ^2.0.0
  # naver_login_sdk: ^1.0.4
  flutter_web_auth_2: ^4.1.0
  uuid: ^4.5.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
